version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: wheelerknight_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wheelerknight_portfolio
      MYSQL_USER: wheelerknight
      MYSQL_PASSWORD: wheelerknight123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - wheelerknight_network

  # Python Flask Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wheelerknight_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=wheelerknight_portfolio
      - DB_USER=wheelerknight
      - DB_PASSWORD=wheelerknight123
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    depends_on:
      - mysql
    networks:
      - wheelerknight_network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wheelerknight_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_ENVIRONMENT=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - wheelerknight_network

  # phpMyAdmin (for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wheelerknight_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - wheelerknight_network

volumes:
  mysql_data:
  backend_uploads:

networks:
  wheelerknight_network:
    driver: bridge
